#!/usr/bin/env python3
"""
Setup script for API Toolkit
Helps configure environment variables
"""

import os
import sys
from pathlib import Path
from getpass import getpass

def setup_env():
    """Interactive setup for .env file"""
    
    env_path = Path(__file__).parent / '.env'
    env_example_path = Path(__file__).parent / '.env.example'
    
    print("API Toolkit Setup")
    print("=" * 50)
    
    if env_path.exists():
        response = input("\n.env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("\nThis will help you set up your API keys.")
    print("Press Enter to skip any service you don't use.\n")
    
    config = {}
    
    # Supabase
    print("SUPABASE CONFIGURATION")
    print("-" * 30)
    
    if input("Configure Supabase Project 1 (main)? (y/N): ").lower() == 'y':
        config['SUPABASE_URL'] = input("  Supabase URL (https://xxx.supabase.co): ").strip()
        config['SUPABASE_SERVICE_ROLE_KEY'] = getpass("  Service Role Key: ").strip()
    
    if input("Configure Supabase Project 2? (y/N): ").lower() == 'y':
        config['SUPABASE_URL_2'] = input("  Supabase URL 2: ").strip()
        config['SUPABASE_SERVICE_ROLE_KEY_2'] = getpass("  Service Role Key 2: ").strip()
    
    if input("Configure Supabase Project 3? (y/N): ").lower() == 'y':
        config['SUPABASE_URL_3'] = input("  Supabase URL 3: ").strip()
        config['SUPABASE_SERVICE_ROLE_KEY_3'] = getpass("  Service Role Key 3: ").strip()
    
    # Other services
    print("\nOTHER SERVICES")
    print("-" * 30)
    
    if input("Configure Klaviyo? (y/N): ").lower() == 'y':
        config['KLAVIYO_API_KEY'] = getpass("  Klaviyo API Key: ").strip()
    
    if input("Configure Render? (y/N): ").lower() == 'y':
        config['RENDER_API_KEY'] = getpass("  Render API Key: ").strip()
    
    if input("Configure BrightData? (y/N): ").lower() == 'y':
        config['BRIGHTDATA_API_KEY'] = getpass("  BrightData API Key: ").strip()
    
    if input("Configure Shopify? (y/N): ").lower() == 'y':
        config['SHOPIFY_SHOP_DOMAIN'] = input("  Shop Domain (xxx.myshopify.com): ").strip()
        config['SHOPIFY_ACCESS_TOKEN'] = getpass("  Access Token: ").strip()
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write("# API Toolkit Environment Variables\n")
        f.write("# Generated by setup.py\n\n")
        
        for key, value in config.items():
            if value:  # Only write non-empty values
                f.write(f"{key}={value}\n")
    
    print(f"\n✅ Configuration saved to {env_path}")
    print("\nYou can now test your configuration:")
    print("  python toolkit.py supabase test")
    print("  python toolkit.py supabase check")
    
    # Test imports
    print("\nTesting imports...")
    try:
        from core.config import Config
        print("✅ Core imports working")
        
        # Check which services are configured
        configured = []
        if config.get('SUPABASE_URL'):
            configured.append('supabase')
        if config.get('KLAVIYO_API_KEY'):
            configured.append('klaviyo')
        if config.get('RENDER_API_KEY'):
            configured.append('render')
        if config.get('BRIGHTDATA_API_KEY'):
            configured.append('brightdata')
        if config.get('SHOPIFY_ACCESS_TOKEN'):
            configured.append('shopify')
        
        if configured:
            print(f"✅ Configured services: {', '.join(configured)}")
        else:
            print("⚠️  No services configured")
    
    except ImportError as e:
        print(f"❌ Import error: {e}")
        print("Run: pip install -r requirements.txt")

if __name__ == "__main__":
    setup_env()